package com.android.shashavs.guardianclient.retrofit.objects

data class News(val id: String,
                val type: String,
                val sectionId: String,
                val sectionName: String,
                val webPublicationDate: String,
                val webTitle: String,
                val webUrl: String,
                val apiUrl: String,
                val isHosted: Boolean,
                val pillarId: String,
                val pillarName: String,
                val fields: Fields?)

data class Fields(val trailText: String,
                  val headline: String,
                  val showInRelatedContent: Boolean,
                  var body: String?,
                  val lastModified: String,
                  val hasStoryPackage: Boolean,
                  val score: Float,
                  val standfirst: String,
                  val shortUrl: String,
                  val thumbnail: String,
                  val wordcount: Int,
                  val commentable: Boolean,
                  val isPremoderated: Boolean,
                  val allowUgc: Boolean,
                  val byline: String,
                  val publication: String,
                  val internalPageCode: String,
                  val productionOffice: String,
                  val shouldHideAdverts: Boolean,
                  val liveBloggingNow: Boolean,
                  val commentCloseDate: String,
                  val starRating: Int)